language: php

php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - composer self-update
    - composer install --dev -n --prefer-source
    - sh -c 'if [ $(php -r "echo PHP_MINOR_VERSION;") -le 4 ]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
    - sh -c 'if [ $(php -r "echo PHP_MINOR_VERSION;") -gt 4 ]; then printf "\n\n\n\n" | pecl install apcu-4.0.2; fi;'

script: php -d apc.enable_cli=1 $(phpenv which phpunit)

after_script:
    - composer require satooshi/php-coveralls=dev-master --dev -n --prefer-source
    - bin/coveralls -v -c ../.coveralls.yml
