language: php

php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - composer self-update
    - composer install --dev -n --prefer-source
    - echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo "apc.enable_cli = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: phpunit -d apc.enable_cli=1

after_script:
    - composer require satooshi/php-coveralls=* --dev -n --prefer-source
    - src/vendors/bin/coveralls
